version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27019:27017
    volumes:
      - ~/apps/mongo:/data/db
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: weatherme
      POSTGRES_DB: weatherme
      APP_DB_USER: docker;
      APP_DB_PASS: docker;
      APP_DB_NAME: docker;
    volumes:
          # - ./db:/docker-entrypoint-initdb.d/
          # - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./db:/docker-entrypoint-initdb.d/
          
  backend:
    image: weathermebackend:latest 
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: backend
    ports:
      - 3000:3000
    depends_on:
      - mongo