version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27019:27017
    volumes:
      - ~/apps/mongo:/data/db
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: weatherme
      POSTGRES_DB: weatherme
  backend:
    image: weathermebackend:latest 
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: backend
    ports:
      - 3000:3000
    depends_on:
      - mongo