version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ~/apps/mongo:/data/db
  mongo-dev:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongodev:/data/db