version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27019:27017
    volumes:
      - ~/apps/mongo:/data/db
  backend:
    image: weathermebackend:latest 
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: backend
    ports:
      - 3000:3000
    depends_on:
      - mongo