openapi: 3.0.0

info:
  version: "1.0.0"
  title: WeatherMe
  description: Front-end website that show's temperature and humidity levels in a specific room to the user client.
  
servers:

  - description: Localhost
    url: http://127.0.0.1:3001
    
paths: 
  /temperature:
      get:
        summary: get temperature
        description: fetch temperature data from mongodb
        operationId: getTemperature
        responses:
          '200':
            description: temperature sensor valid response
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/temperature'
                 
      post:
        summary: post temperature
        description: post temperature data from sensors
        operationId: postTemperature
        responses:
          '201':
            description: post temperature sucess response
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/temperature'
                example:
                  location: casa
                  date: 123456
                  temperature: 1234
                     
components:
  schemas:
    temperature:
      type: object
      required:
        - id
        - location
        - date
        - temperature
      properties:
        id:
          type: integer
        location:
          type: string
        date:
          type: integer
        temperature:
          type: integer
      example:
        schemas:
          - id: 123
      description: Type of TemperatureSensor object